spring:
  application:
    name: chatservice

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/SPSHPAU
          jwk-set-uri: http://keycloak:8080/realms/SPSHPAU/protocol/openid-connect/certs

  data:
    mongodb:
      username: spshpau
      password: admin
      host: mongodb
      port: 27017
      database: chat
      authentication-database: admin

server:
  port: 8091

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

jwt:
  auth:
    converter:
      resource-id: spshpau-rest-api
      principle-attribute: sub

application:
  cofig:
    userclienturl: http://userservice:8090/api/v1/interactions
